#!/usr/bin/env python
"""Regenerate `research/configs/repositories.yaml` (PHASE 21).

    python research/scripts/repo_manifest.py

The cloned repositories themselves live outside git (they are upstream code, on
the WSL-native volume). This manifest is what *is* tracked: the exact remote,
commit and local-modification state of every one, so a result can be traced
back to the code that produced it.

Run this whenever you clone a new research repo or patch an existing one.
"""

from __future__ import annotations

import subprocess
from datetime import date
from pathlib import Path

REPO_ROOT = Path("/home/hoanguyen/ncs-data/repositories")
OUTPUT = Path(__file__).resolve().parents[1] / "configs" / "repositories.yaml"

#: Groups excluded from the manifest on `main`. Development tooling is not a
#: research dependency, and its notes live on the `phase1-tooling` branch.
SKIP_GROUPS = {"tooling"}


def git(path: Path, *args: str) -> str:
    try:
        result = subprocess.run(
            ["git", "-C", str(path), *args], capture_output=True, text=True, timeout=20
        )
        return result.stdout.strip() if result.returncode == 0 else "?"
    except Exception:
        return "?"


def human_size(path: Path) -> str:
    try:
        return subprocess.run(
            ["du", "-sh", str(path)], capture_output=True, text=True, timeout=60
        ).stdout.split()[0]
    except Exception:
        return "?"


def discover(root: Path) -> list[Path]:
    """Every git checkout at depth 1 or 2 under the repositories root."""
    found = []
    for entry in sorted(root.iterdir()):
        if not entry.is_dir():
            continue
        if (entry / ".git").is_dir():
            found.append(entry)
        elif entry.name not in SKIP_GROUPS:
            # one level of grouping, e.g. repositories/<group>/*
            found.extend(sorted(c for c in entry.iterdir() if (c / ".git").is_dir()))
    return found


def main() -> None:
    if not REPO_ROOT.is_dir():
        raise SystemExit(f"repository root not found: {REPO_ROOT}")

    lines = [
        "# Auto-generated by research/scripts/repo_manifest.py -- do not edit by hand.",
        "# Records the exact upstream state of every cloned research repository (PHASE 21).",
        f"# Regenerated: {date.today().isoformat()}",
        "repositories:",
    ]

    for path in discover(REPO_ROOT):
        name = path.relative_to(REPO_ROOT)
        dirty = git(path, "status", "--porcelain")
        lines += [
            f"  - name: {name}",
            f"    path: research/repositories/{name}",
            f"    remote: {git(path, 'config', '--get', 'remote.origin.url')}",
            f"    commit: {git(path, 'rev-parse', 'HEAD')}",
            f"    branch: {git(path, 'rev-parse', '--abbrev-ref', 'HEAD')}",
            f"    size: {human_size(path)}",
            f"    local_modifications: {'yes' if dirty else 'none'}",
        ]
        if dirty:
            lines.append("    # WARNING: upstream checkout has uncommitted changes.")
            lines.append("    # Move them to an experiment branch or a patch file -- see")
            lines.append("    # research/REPOSITORIES.md.")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUTPUT} ({len(discover(REPO_ROOT))} repositories)")


if __name__ == "__main__":
    main()
